# Start from the official Airflow image
FROM apache/airflow:2.6.3
# Install Google Cloud SDK and any other packages
RUN pip install google-cloud-storage

# If you have other dependencies, list them here
# RUN pip install <other-dependency>
